// All roadmap content lives here so the page component stays readable.
// Each phase: number, title, time, accent (Tailwind class for the dot/badge),
// why, learn[], videos[{label, href, main}], practice[], project, ready.

// "Phase 0" -> "phase-0". The URL slug for each phase's page.
export const phaseSlug = (n) => n.toLowerCase().replace(/\s+/g, '-')

// Short title without the "— subtitle" tail, e.g. "Python — the foundation" -> "Python".
export const phaseShortTitle = (p) => p.title.split(/[—:]/)[0].trim()

export const phases = [
  {
    n: 'Phase 0',
    title: 'Get set up',
    time: '1–2 weeks',
    why: 'Getting your computer ready, so nothing annoying gets in your way later.',
    learn: [
      'Install <b>Python</b> and <b>VS Code</b> (the program where you write your code).',
      'Learn the <b>terminal</b> (a text window where you type commands to tell the computer what to do).',
      'Get comfortable typing without looking at the keyboard (try monkeytype.com).',
      'Learn to copy an error message into Google and read the answers. This is a real skill that everyone uses, every day.',
    ],
    setup: [
      {
        title: 'Install Python',
        links: [
          { tag: 'Windows', label: 'Install Python on Windows (and fix the PATH problem)', href: 'https://www.youtube.com/results?search_query=how+to+install+python+on+windows+add+to+path+2026' },
          { tag: 'macOS', label: 'Install Python on a Mac', href: 'https://www.youtube.com/results?search_query=how+to+install+python+on+mac+2026' },
          { tag: 'Download', label: 'python.org — official downloads', href: 'https://www.python.org/downloads/' },
        ],
      },
      {
        title: 'Install VS Code (your code editor)',
        links: [
          { tag: 'Windows', label: 'Install VS Code on Windows', href: 'https://www.youtube.com/results?search_query=how+to+install+vs+code+on+windows+2026' },
          { tag: 'macOS', label: 'Install VS Code on a Mac', href: 'https://www.youtube.com/results?search_query=how+to+install+vs+code+on+mac+2026' },
          { tag: 'Download', label: 'code.visualstudio.com', href: 'https://code.visualstudio.com/' },
        ],
      },
      {
        title: 'Install Git (you’ll need it in Phase 2)',
        links: [
          { tag: 'Windows', label: 'Install Git on Windows', href: 'https://www.youtube.com/results?search_query=how+to+install+git+on+windows+2026' },
          { tag: 'macOS', label: 'Install Git on a Mac', href: 'https://www.youtube.com/results?search_query=how+to+install+git+on+mac+2026' },
          { tag: 'Download', label: 'git-scm.com', href: 'https://git-scm.com/downloads' },
        ],
      },
    ],
    callout: {
      kind: 'lowspec',
      html: "<b>No powerful computer? You can still start.</b> An old laptop is fine all the way up to Phase 8. If all you have is a phone, write and run real code in the browser with <b>Replit</b> (replit.com) or <b>Google Colab</b> (colab.research.google.com) — nothing to install.",
    },
    videos: [
      { main: true, label: 'Harvard CS50 — Lecture 0: what programming actually is', href: 'https://www.youtube.com/watch?v=3LPJfIKxwWc' },
      { label: 'freeCodeCamp — the terminal / command line for beginners', href: 'https://www.youtube.com/watch?v=uwAqEzhyjtw' },
    ],
    practice: [
      'Install Python and make it print the words <i>Hello, world</i>.',
      'In the terminal: make a folder, put a file in it, show what is inside, then delete it.',
      'Do 3 short typing lessons.',
      'Type one wrong letter on purpose, read the red error, and Google it.',
    ],
    project: 'A tiny Python program that asks your name and favourite subject, then prints a pretty "hello card". The goal is just to see your setup working.',
    ready: 'You can open VS Code, type a small program, and run it in the terminal without help.',
  },
  {
    n: 'Phase 1',
    title: 'Python — the foundation',
    time: '2–4 months',
    why: 'Python is your first language. It reads almost like English, so it is the kindest place to start. It is also the language the whole world uses for AI.',
    learn: [
      'Basic <b>syntax</b> (= the spelling and grammar rules of a language): variables, numbers, text, input and output.',
      'Making choices and repeating things: <code>if / else</code>, <code>for</code>, <code>while</code>.',
      'Ways to hold many things: lists, dictionaries, sets.',
      'Functions: a block of code you can reuse, so you don’t write the same thing twice.',
      'Files: reading and writing text files.',
      'Mistakes: how to catch errors (<code>try / except</code>) and read what they say.',
      '<b>OOP</b> (= a way to group code into "objects" that hold both data and actions). This one feels hard at first — that is completely normal, go slow.',
    ],
    videos: [
      { main: true, label: 'Programming with Mosh — Python for Beginners (≈6 hrs)', href: 'https://www.youtube.com/watch?v=K5KVEU3aaeQ' },
      { label: 'freeCodeCamp — Learn Python, Full Course', href: 'https://www.youtube.com/watch?v=rfscVS0vtbw' },
      { label: 'Corey Schafer — Python Tutorials (playlist, great for OOP)', href: 'https://www.youtube.com/playlist?list=PL-osiE80TeTskrapNbzXhwoFUiLCjGgY7' },
      { label: 'Urdu/Hindi — CodeWithHarry: The Ultimate Python Course', href: 'https://www.youtube.com/watch?v=UrsmFxEIp5k' },
    ],
    practice: [
      'FizzBuzz (print numbers, but with a twist).',
      'A program that turns Celsius into Fahrenheit.',
      'Count the vowels in a word.',
      'A small phone-book using a dictionary.',
      'Read a text file and count how many words it has.',
    ],
    project: 'A <b>To-Do app in the terminal</b>: add tasks, see them, mark them done, delete them, and save them to a file so they are still there next time. Remember this app — you will rebuild it bigger later!',
    ready: 'You can write a small program from a blank file by yourself, without copying a video line-by-line.',
  },
  {
    n: 'Phase 2',
    title: 'Computer science basics',
    time: '3–6 months',
    why: 'These are the thinking skills behind coding. They are exactly the part that AI cannot do for you — so they make you valuable.',
    learn: [
      '<b>Git</b> (= a tool that saves every version of your code so you can undo mistakes) and <b>GitHub</b> (= a website that keeps your code online). Every project from now lives in a <b>repo</b> (= a project folder Git watches).',
      'Ways to store data: lists, stacks, queues, <b>hash maps</b> (= super-fast "name → value" lookups), and later trees and graphs.',
      'Step-by-step methods (algorithms): searching, sorting, and <b>recursion</b> (= a function that calls itself to solve a smaller piece of the same problem).',
      '<b>Big-O</b> (= a simple way to say how much slower your code gets when the data gets big).',
    ],
    videos: [
      { main: true, label: 'Harvard CS50 — full course (free)', href: 'https://www.youtube.com/watch?v=8mAITcNt710' },
      { label: 'freeCodeCamp — Data Structures & Algorithms, full course', href: 'https://www.youtube.com/watch?v=8hly31xKli0' },
      { label: 'Traversy Media — Git & GitHub crash course', href: 'https://www.youtube.com/watch?v=SWYqp7iY_Tc' },
      { label: 'NeetCode — how to solve coding problems (channel)', href: 'https://www.youtube.com/@NeetCode/videos' },
    ],
    practice: [
      'Write a "binary search" (a fast way to find a number in a sorted list).',
      'Reverse a word without using the built-in reverse.',
      'Solve 10 <b>Easy</b> problems on LeetCode (Easy only — be kind to yourself).',
      'Put all your old projects on GitHub, each with a short <b>README</b> (= a note that says what the project does).',
    ],
    project: 'A GitHub page with 15–20 small problems you solved, sorted by topic. This is the start of your "proof" that you can code.',
    ready: 'You can save and upload code to GitHub on your own, and you understand why one solution is faster than another.',
  },
  {
    n: 'Phase 3',
    title: 'Maths for AI — later, optional',
    time: 'come back to this much later',
    why: 'Don’t worry about this one yet. It only matters much later, if you decide to BUILD AI rather than just use it — and most of it is maths you’ll meet naturally in college. Right now, keep your focus on building.',
    learn: [
      'For now, just know the <b>names</b> so they aren’t scary later: <b>linear algebra</b> (maths of vectors and matrices), <b>calculus</b> (slopes and how things change), and <b>statistics</b> (averages, spread, and chance).',
      'You don’t need to study these now. You’ll see <i>why</i> they matter once you start building AI in Phase 9 — and that’s the right time to learn them properly.',
      'If maths is your thing and you’re curious, the videos below are the friendliest intros out there. Totally optional.',
    ],
    callout: {
      kind: 'note',
      html: '<b>Important:</b> you can build websites and full apps with almost no advanced maths. This page is here so you know the maths exists and where it fits — not as homework. Skip ahead to Phase 4 and keep building; come back to this only when you reach the deep-AI part.',
    },
    videos: [
      { main: true, label: '3Blue1Brown — Essence of Linear Algebra (save for later)', href: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab' },
      { label: '3Blue1Brown — Essence of Calculus (save for later)', href: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr' },
      { label: 'StatQuest — Statistics Fundamentals (save for later)', href: 'https://www.youtube.com/playlist?list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9' },
    ],
    practice: [
      'Nothing to do here right now. Keep your momentum and move to Phase 4.',
      'When you reach Phase 9 and want to go deep on AI, come back and watch the videos above.',
    ],
    project: 'No project for this phase yet. Your “project” is to not get stuck here — move on and keep building.',
    ready: 'You know this maths exists and where it fits in. That’s all you need for now — on to Phase 4.',
  },
  {
    n: 'Phase 4',
    title: 'Web basics: HTML, CSS, JavaScript',
    time: '3–4 months',
    why: 'Now you make things people can actually SEE in a web browser. We use the plain building blocks first — no shortcuts yet, so you really understand how the web works.',
    learn: [
      '<b>HTML</b> (= gives a web page its bones — the headings, text, buttons, forms).',
      '<b>CSS</b> (= the paint and layout — colours, spacing, and making it look good on a phone too). This "looks good on any screen" idea is called <b>responsive design</b>.',
      '<b>JavaScript</b> (= makes the page DO things when you click or type). You’ll meet the <b>DOM</b> (= the live page that JavaScript can change) and <b>async</b> code (= code that waits for slow things, like the internet, without freezing the page).',
    ],
    videos: [
      { main: true, label: 'freeCodeCamp — HTML & CSS full course for beginners', href: 'https://www.youtube.com/watch?v=mU6anWqZJcc' },
      { label: 'Kevin Powell — the CSS master (channel)', href: 'https://www.youtube.com/@KevinPowell/videos' },
      { label: 'Web Dev Simplified — JavaScript (channel)', href: 'https://www.youtube.com/@WebDevSimplified/videos' },
      { label: 'The Net Ninja — Modern JavaScript (playlist)', href: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9haFPT7J25Q9GRB_ZkFrQAc' },
      { label: 'Traversy Media — JavaScript crash course', href: 'https://www.youtube.com/watch?v=hdI2bqOjy3c' },
    ],
    practice: [
      'Build a simple recipe page.',
      'Make 3 cards sit side by side (try Flexbox, then Grid).',
      'Add a button that switches between dark and light colours.',
      'Pull a joke from a free <b>API</b> (= a way for two programs to share data) and show it on the page.',
    ],
    project: 'Your own portfolio website (about you), with one fun interactive thing, put <b>online for free</b> with GitHub Pages. To <b>deploy</b> (= put your work on the internet for anyone to see) — that is a big, exciting moment. Your first thing on the real web!',
    ready: 'You can build a small web page from scratch and put it online with a real link you can share.',
  },
  {
    n: 'Phase 5',
    title: 'React — a frontend framework',
    time: '2–4 months',
    why: 'This is how real companies build modern websites. Start ONLY after plain JavaScript feels okay — React is much easier when the basics are solid.',
    learn: [
      '<b>React</b> (= a popular JavaScript <b>framework</b> — a ready-made toolbox — for building screens out of small reusable pieces).',
      '<b>Components</b> (= the small reusable pieces), <b>props</b> (= info you hand to a piece), and <b>state</b> (= info a piece remembers and can change).',
      '<b>Hooks</b> like useState and useEffect (= special React helpers that give pieces powers like memory).',
      '<b>Tailwind CSS</b> (= a fast way to style with tiny labels) and later <b>TypeScript</b> (= JavaScript that warns you about mistakes early).',
    ],
    setup: [
      {
        title: 'Install Node.js and npm (React needs these)',
        links: [
          { tag: 'Windows', label: 'Install Node.js and npm on Windows', href: 'https://www.youtube.com/results?search_query=how+to+install+node+js+and+npm+on+windows+2026' },
          { tag: 'macOS', label: 'Install Node.js and npm on a Mac', href: 'https://www.youtube.com/results?search_query=how+to+install+node+js+and+npm+on+mac+2026' },
          { tag: 'Download', label: 'nodejs.org — get the LTS version', href: 'https://nodejs.org/' },
        ],
      },
    ],
    videos: [
      { main: true, label: 'The Net Ninja — Full Modern React Tutorial (playlist)', href: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9gZD-Tvwfod2gaISzfRiP9d' },
      { label: 'JavaScript Mastery — build real React projects (channel)', href: 'https://www.youtube.com/@javascriptmastery/videos' },
      { label: 'Programming with Mosh — React for Beginners', href: 'https://www.youtube.com/watch?v=SqcY0GlETPk' },
      { label: 'Traversy Media — TypeScript crash course (later)', href: 'https://www.youtube.com/watch?v=BCg4U1FzODs' },
    ],
    practice: [
      'A counter with + and − buttons.',
      'A list where you can add and delete items.',
      'Show data from an API, with a "loading…" message and an error message.',
      'A small 3-page site you can click between.',
    ],
    project: 'A <b>weather app</b> or <b>movie-search app</b> in React that uses a real API, has pages, and is styled with Tailwind. Put it online with <b>Vercel</b> (= free hosting for the front of a website).',
    ready: 'You can build a multi-page React app that fetches real data and shows it nicely.',
  },
  {
    n: 'Phase 6',
    title: 'Backend — the server side',
    time: '3–4 months',
    why: 'The backend is the hidden brain: it does the thinking and remembers the data. We stay in Python, so you build on what you already know.',
    learn: [
      'What a backend does: it gets a request, thinks, talks to the database, and sends an answer back.',
      '<b>REST API</b> (= a simple, standard way for programs to ask each other for things) using the actions GET, POST, PUT, DELETE.',
      '<b>CRUD</b> (= the four basic things you do to data: Create, Read, Update, Delete).',
      'Login, using a <b>token / JWT</b> (= a secure digital pass that proves who is logged in).',
      'Pick one tool: <b>FastAPI</b> (= modern, fast, and great for AI — recommended) or <b>Django</b> (= bigger, comes with lots built in).',
    ],
    videos: [
      { main: true, label: 'freeCodeCamp — FastAPI / Python API development (full course)', href: 'https://www.youtube.com/watch?v=0sOvCWFmrtA' },
      { label: 'freeCodeCamp — Django full course for beginners', href: 'https://www.youtube.com/watch?v=rHux0gMZ3Eg' },
      { label: 'The Net Ninja — Django (playlist)', href: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9MFu7lcd_QqgvBcN_zUFFXC' },
      { label: 'Official FastAPI tutorial (one of the best anywhere)', href: 'https://fastapi.tiangolo.com/learn/' },
    ],
    practice: [
      'A tiny API that answers "hello".',
      'Add Create / Read / Update / Delete for a list of items.',
      'Add a simple login with a token.',
      'Open your API’s automatic test page (called Swagger) and try it.',
    ],
    project: 'Turn your Phase 1 To-Do app into a real online API with full CRUD and a login. Same app — now living on a server!',
    ready: 'You can build an API that stores items and handles a basic login.',
  },
  {
    n: 'Phase 7',
    title: 'Databases',
    time: '1–2 months',
    why: 'Every real app needs to remember things even after it is closed. That is what a database is for.',
    learn: [
      '<b>SQL</b> (= the language for asking a database questions): SELECT, WHERE, INSERT, UPDATE, DELETE, and <b>JOIN</b> (= joining two tables together).',
      '<b>PostgreSQL</b> (= a popular, powerful, free database).',
      'Good table design and <b>normalization</b> (= not storing the same thing twice).',
      '<b>ORM</b> (= a tool that lets you use the database with normal code instead of database commands).',
      'Easy modern option: <b>Supabase</b> (= a ready-made online database with login built in).',
    ],
    videos: [
      { main: true, label: 'freeCodeCamp — SQL full course for beginners', href: 'https://www.youtube.com/watch?v=HXV3zeQKqGY' },
      { label: 'The Net Ninja — SQL for beginners (playlist)', href: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9iu6mD3EW1Qs8b9X1Sz7gPN' },
      { label: 'freeCodeCamp — Supabase crash course', href: 'https://www.youtube.com/watch?v=dU7GwCOgvNY' },
    ],
    practice: [
      'On paper, design 3 tables (users, posts, comments) and draw how they connect.',
      'Write a question that finds and sorts some rows.',
      'Write a JOIN across two tables.',
      'Connect your Phase 6 API to a real database.',
    ],
    project: 'Add a real database to your backend so the data stays after restart — and link it (one user has many tasks).',
    ready: 'Your To-Do app keeps its data forever, in a real database, linked to each user.',
  },
  {
    n: 'Phase 8',
    title: 'Full app, online',
    time: '2–3 months',
    why: 'The big one. You join the front, the back, and the database into ONE real app and put it on the internet. After this, you are a full-stack developer.',
    learn: [
      'Connect the three parts: React (front) ↔ your API (back) ↔ database.',
      'Build one complete app with login, from start to finish.',
      'Put it online: front on Vercel, back on <b>Render or Railway</b> (= free hosting for backends), database online.',
      'Keep secrets in <b>environment variables</b> (= passwords kept outside your code).',
    ],
    videos: [
      { main: true, label: 'JavaScript Mastery — full-stack projects (channel)', href: 'https://www.youtube.com/@javascriptmastery/videos' },
      { label: 'freeCodeCamp — full-stack courses (channel)', href: 'https://www.youtube.com/@freecodecamp/search?query=full%20stack' },
      { label: 'Fireship — short, clear deployment videos (channel)', href: 'https://www.youtube.com/@Fireship/videos' },
    ],
    practice: [
      'Connect your React app to your own API.',
      'Hide pages from people who are not logged in.',
      'Move all secrets into environment variables.',
      'Do one real deploy — front AND back.',
    ],
    project: '<b>Your big project:</b> one complete, online app that solves a small real problem (a study-notes app, an expense tracker, a habit tracker). It must have a login, a database, a React front, an API back, a <b>live link anyone can open</b>, and a clear README with screenshots. <b>This one project is worth more than ten tutorials.</b>',
    ready: 'You have ONE finished app online that you can send to anyone as a link. You are now full-stack capable.',
  },
  {
    n: 'Phase 9',
    title: 'Using AI in your apps',
    time: 'ongoing',
    why: 'The fun, useful part of AI — and the part you can actually do now. The goal here is to understand how these tools work and add an AI feature to your own app. The deep "build AI from scratch" stuff is a separate, much-later road.',
    learn: [
      'First, understand the basics in plain words: what an <b>LLM</b> is (= a big AI model that reads and writes text, like ChatGPT or Claude), what a <b>token</b> is (= the small chunks of text an LLM reads and writes, a bit like syllables), and roughly how it works (it predicts the next token, over and over).',
      'What these models are good at and where they go wrong — why they sometimes confidently make things up (<b>hallucinate</b>), and why clear instructions matter.',
      '<b>Prompt engineering</b> (= writing good instructions so the AI gives good answers). Small wording changes make a big difference.',
      'How to call an AI from your code: send a prompt to an LLM’s <b>API</b> and show the answer in your app — for example, add a simple chatbot or “summarise this” button to your Phase 8 project.',
    ],
    callout: {
      kind: 'note',
      html: '<b>Want to go deeper into building AI itself</b> — training your own models, neural networks, the maths? That’s a real path, but it comes much later and needs the Phase 3 maths first. For now, focus on <i>using</i> AI well. The optional links below are there for when you’re ready.',
    },
    videos: [
      { main: true, label: 'What is an LLM / how ChatGPT works — simple explainer', href: 'https://www.youtube.com/watch?v=zjkBMFhNj_g' },
      { label: 'DeepLearning.AI — free short courses (Prompt Engineering, building with LLMs)', href: 'https://www.deeplearning.ai/courses/' },
      { label: 'Later & optional — 3Blue1Brown: Neural Networks (the intuition)', href: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi' },
      { label: 'Later & optional — Andrej Karpathy: Neural Networks, Zero to Hero', href: 'https://karpathy.ai/zero-to-hero.html' },
    ],
    practice: [
      'Take one task and write it 5 different ways as prompts — compare how the answers change.',
      'Get an API key from a free/cheap LLM and make a tiny script that sends a prompt and prints the reply.',
      'Add one small AI feature to your Phase 8 app — a chatbot, or a “summarise this” button.',
    ],
    project: 'Add a real AI feature to your Phase 8 app — something a user can actually click and use. That’s the goal for now. (Building and training your own models is a later, optional road.)',
    ready: 'You can explain in simple words what an LLM and a token are, and you’ve shipped one working AI feature in an app.',
  },
  {
    n: 'Phase 10',
    title: 'Keep growing',
    time: 'forever',
    why: 'You never really finish — and that is the fun part. Keep building, keep sharing, keep learning.',
    learn: [
      'Testing, clean code, and a little system design (how big apps are built).',
      '<b>Open source</b> (= public projects anyone can help improve) — make your first small contribution on GitHub.',
      'A strong portfolio: a tidy GitHub plus a personal site with 3–4 real projects.',
      'Keep improving your English — most of the best material is in English, and it opens doors.',
    ],
    videos: [
      { main: true, label: 'Fireship — what’s new in tech (channel)', href: 'https://www.youtube.com/@Fireship/videos' },
      { label: 'ThePrimeagen — a senior developer’s view (channel)', href: 'https://www.youtube.com/@ThePrimeagen/videos' },
      { label: 'NeetCode — interviews & system design (channel)', href: 'https://www.youtube.com/@NeetCode/videos' },
      { label: 'ArjanCodes — clean Python (channel)', href: 'https://www.youtube.com/@ArjanCodes/videos' },
    ],
    practice: [
      'Write one blog post or README explaining something you built.',
      'Make one small open-source contribution.',
      'Keep your GitHub green — code a little, often.',
    ],
    project: 'Keep your portfolio fresh: 3–4 real projects, each with a live link and a clear README.',
    ready: 'You can learn any new tool on your own now — that is the real skill.',
  },
]

export const habits = [
  ['Use Git from day one', 'Your projects slowly add up into a portfolio by themselves.'],
  ['Build, don’t just watch', 'Watching feels like progress, but building is the real thing.'],
  ['Rebuild from memory', 'After a video, close it and make the same thing again yourself.'],
  ['One main tutorial per phase', 'Don’t get lost jumping between many videos.'],
  ['Code a little every day', 'One hour daily beats ten hours once a week.'],
  ['Keep a learning diary', 'Write what you learned each week — it sticks better.'],
  ['Join a community', 'A Discord group keeps you motivated and helps when stuck.'],
  ['Read other people’s code', 'On GitHub — you learn a lot from how others solve things.'],
]

export const wordBank = [
  ['Boilerplate', 'the same basic starter code you write again and again before the real work starts'],
  ['Syntax', 'the spelling and grammar rules of a programming language'],
  ['Terminal', 'a text window where you type commands to control the computer'],
  ['Git / GitHub', 'a tool that saves every version of your code; GitHub stores it online'],
  ['Repo', 'a project folder that Git keeps track of'],
  ['Framework', 'a ready-made toolbox that does common work for you'],
  ['Frontend', 'the part of an app you see and click, in the browser'],
  ['Backend', 'the hidden part on a server that does the logic and stores data'],
  ['Server', 'a computer that runs your app and answers users’ requests'],
  ['Full-stack', 'able to build both the frontend and the backend'],
  ['API', 'a way for two programs to talk and share data'],
  ['REST API', 'a common, simple API style using normal web requests'],
  ['CRUD', 'the four basic data actions: Create, Read, Update, Delete'],
  ['DOM', 'the live structure of a web page that JavaScript can change'],
  ['Async', 'code that can wait for slow things without freezing everything'],
  ['SQL', 'the language used to ask a database for data'],
  ['ORM', 'talk to a database using normal code instead of database commands'],
  ['Token / JWT', 'a secure digital pass that proves a user is logged in'],
  ['Deploy', 'to put your app on the internet so anyone can use it'],
  ['Big-O', 'how much slower code gets as the data grows'],
  ['Recursion', 'when a function calls itself to solve a smaller piece'],
  ['LLM', 'a large AI model that reads and writes text, like ChatGPT or Claude'],
  ['Token', 'the small chunks of text an LLM reads and writes — a bit like syllables'],
  ['Prompt', 'the instruction you give to an AI'],
  ['Hallucinate', 'when an AI confidently makes something up that isn’t true'],
  ['Neural network', 'a brain-inspired system that learns from examples (the deep, later stuff)'],
]
